services:
  python-manager:
    build:
      context: ./img
      dockerfile: dockerfile
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    container_name: python_3_12_trixie
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
      # - ./private:/private
    working_dir: /private
    tty: true
    # user: appuser
