services:
  python-manager:
    build:
      context: ./img
      dockerfile: dockerfile
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    container_name: python_3_12_trixie
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
      - ./private:/private
    working_dir: /private
    tty: true
    network_mode: host
    user: root
