services:
  python-manage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_3_12_trixie
    volumes:
      - ./private:/private
    working_dir: /private
    tty: true
    user: appuser
