FROM openjdk:26-jdk-trixie

ENV POPULATION_SIZE=250
ENV DATASET_NAME=synthea_florida
ARG WORKSPACE_DIR

VOLUME /private

RUN mkdir -p /app/synthea $OUTPUT_DIR

WORKDIR  /app/synthea

RUN curl -L -o /app/synthea/synthea-with-dependencies.jar \
    https://github.com/synthetichealth/synthea/releases/download/master-branch-latest/synthea-with-dependencies.jar

COPY ./synthea.properties /app/synthea/
COPY ./entrypoint.sh /app/

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["-p" , "50"]
