FROM python:3.12.11-trixie

VOLUME /private

# Install system dependencies and tools (including just)
RUN apt-get update && apt-get install -y --no-install-recommends \
curl \
ca-certificates \
build-essential \
dnsutils iputils-ping \
just \
neovim tmux pinfo htop mc fish \
&& rm -rf /var/lib/apt/lists/*

# Install uv via apt (official Astral package)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN pip install tsrc fastapi uvicorn

# Add SSH config directory for the user
ADD ssh_config /root/.ssh
RUN chmod 700 /root/.ssh && chmod 600 /root/.ssh/*

COPY ./entrypoint.sh /app/
RUN chmod +x /app/entrypoint.sh


ENTRYPOINT ["/app/entrypoint.sh"]

# Default command
CMD ["fish"]
