FROM python:3.12.11-trixie

VOLUME /private

# Install system dependencies and tools (including just)
RUN apt-get update && apt-get install -y --no-install-recommends \
curl \
ca-certificates \
build-essential \
dnsutils iputils-ping net-tools \
just \
neovim tmux pinfo htop mc fish \
&& rm -rf /var/lib/apt/lists/*

# Install code-server (VS Code headless)
RUN curl -fsSL https://code-server.dev/install.sh | sh
RUN code-server --install-extension nefrob.vscode-just-syntax
RUN code-server --install-extension ms-python.python
RUN code-server --install-extension ms-python.debugpy
RUN code-server --install-extension python-beautifier.python-beautifier

# Expose code-server port
EXPOSE 8080

# Install uv via apt (official Astral package)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN pip install tsrc fastapi uvicorn pandas sqlalchemy click

# Add SSH config directory for the user
ADD ssh_config /root/.ssh
RUN chmod 700 /root/.ssh && chmod 600 /root/.ssh/*

COPY ./entrypoint.sh /app/
RUN chmod +x /app/entrypoint.sh

# Default config directory
RUN mkdir -p /root/.config/code-server

# Optional: provide a config file

ENTRYPOINT ["/app/entrypoint.sh"]

# Default command
CMD ["fish"]
