FROM python:3.12.11-trixie

VOLUME /private
ENV WORKSPACE_DIR=/private/abx-ltd/workspace

# Install system dependencies and tools (including just)
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    build-essential \
    dnsutils iputils-ping \
    just \
    neovim tmux pinfo htop mc fish \
 && rm -rf /var/lib/apt/lists/*

# Install uv via apt (official Astral package)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN pip install tsrc fastapi

# Add SSH config directory for the user
RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh
RUN mkdir -p /private/abx-ltd

# Add a default SSH config (you can override via volume later)
COPY ssh_config /root/.ssh/config
COPY gh_abx.pub /root/.ssh/gh_abx.pub
COPY gh_ncs.pub /root/.ssh/gh_ncs.pub

RUN chmod 600 /root/.ssh/*

# Set working directory
WORKDIR $WORKSPACE_DIR

# Default command
CMD ["bash"]
