FROM python:3.12.11-trixie

# Install system dependencies and tools (including just)
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    build-essential \
    dnsutils \
    just \
    neovim tmux pinfo htop mc \
 && rm -rf /var/lib/apt/lists/*

# Install uv via apt (official Astral package)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN pip install tsrc fastapi
# Create a non-root user
RUN useradd -m appuser

# Create the /private directory and assign ownership
RUN mkdir -p /private/abx-ltd && chown -R appuser:appuser /private

# Switch to non-root user by default
USER appuser

# Set working directory
WORKDIR /private

# Default command
CMD ["bash"]
